version: '3.9'

services:
  api:
    container_name: nest-api
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '3000:3000'
    env_file:
      - .env
      - '4000:4000'
    environment:
      - MONGODB_URI=mongodb://mongo:27017/weathersdb
    depends_on:
      - mongo
      
  mongo:
    container_name: mongo-db
    image: mongo:6
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
