name: Build and Deploy Backend QA

on:
  workflow_dispatch:

env:
  ACR_NAME: weatherlyrg
  IMAGE_NAME: poc-weather-api

jobs:
  build-and-deploy-qa:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to ACR
        run: az acr login --name $ACR_NAME

      - name: Generate Version from Changeset
        run: |
          npx changeset version
          VERSION=$(node -p "require('./package.json').version")
          echo "IMAGE_TAG=$VERSION" >> $GITHUB_ENV

      - name: Build and push image
        run: |
          IMAGE=$ACR_NAME.azurecr.io/$IMAGE_NAME:${{ env.IMAGE_TAG }}
          echo "Building Docker image: $IMAGE"
          docker build -t $IMAGE .
          docker push $IMAGE
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Wait for manual approval
        uses: hmarr/auto-approve-action@v2
        if: false # Solo para mostrar, usar GitHub Environments para aprobación real

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'weatherly-api-qa'
          images: ${{ env.IMAGE }}
